TSE Review 01.
wrakc/apple-clone pull request #4
Opened 2020-05-13 19:30 UTC by wrakc

- Added linter files;
- Added gitignore files;
- Added the main files (index, and styles);
- Created the main index code and added the pictures;
- Styled the elements accordingly to the website cloned;
- Updated and fixed the readme file.
- Fixed linter issues using local linter

2020-05-13 19:32 UTC, wrakc commented
I am getting the following error at the GitHub check for linter errors:

_Error: ENOENT: no such file or directory, open '/src/src/stylelint.config.js'_

So I locally fixed the linter errors.

2020-05-14 00:34 UTC, trekab requested changes
# Changes Required!
Hi @wrakc, you have done a very commendable job on this project! :clap: You have met most of the requirements. However, there are a few issues you need to fix to have this project approved.
These are;
- [x] Your clone appears to be broken on large screens. ([screenshot](https://github.com/trekab/images/blob/master/appleclone.png?raw=true) from my screen). 
- [x] You have to resolve the stickler error you are facing.

__Kindly work on the highlighted issues and submit another code review request.__
_Feel free to contact me on slack for any assistance regarding this review_ :wink: 
__Treasure Kabareebe__
[GitHub](https://github.com/trekab) | [LinkedIn](https://www.linkedin.com/in/treasure-kabareebe/) | [Twitter](https://twitter.com/TKabareebe)

2020-05-14 14:40 UTC, wrakc commented
Thanks, I will make the changes as suggested!

2020-05-15 12:27 UTC, wrakc commented
I fixed the issues with the stickler clone and fixed the margins of the background image when appearing in high-resolution screens, also closed the pull request that I created and reopened this one.

2020-05-16 04:17 UTC, rammazzoti2000 requested changes
### Hello @wrakc :wave: great work this far :rocket: 
You used HTML semantic in your project, as well  CSS background and gradients, great job on that.
Also the Readme files is descriptive, Pull Request as well, commits short and meaningful, overall the project looks professional.
There are still some issues left before approving this project, check the comments below :point_down: 
### :stop_sign: Required Changes :construction: :construction_worker: 
- [x] Your project still has some horizontal overflow left, please see the inline comments for the fix
- [x]   CSS bad practices ([article for support ](https://speckyboy.com/good-bad-css-practices)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/css_bad_practices_requirement.png) from Pathwright)
   *  No repeating rule, see the inline comments for more details
### <em>Kindly fix the REQUIRED issues and send another code review request.

Cheers and Happy coding! :clap: 

Code review by Alexandru Bangau

(Feel free to contact me on slack by the handle of alexandru if you have any additional question)</em>
### :stop_sign: Status: Required Changes

2020-05-16 04:17 UTC, rammazzoti2000 commented on assets/styles.css
> +  min-width: 1440px;
Causing horizontal overflow, change it to max-width instead to fix the issue

2020-05-16 04:17 UTC, rammazzoti2000 commented on assets/styles.css
> +  width: 358px;
last step to fix horizontal overflow is to set this width to 99%

2020-05-16 04:17 UTC, rammazzoti2000 commented on assets/styles.css
> +  display: flex;
CSS bad practices ([article for support ](https://speckyboy.com/good-bad-css-practices)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/css_bad_practices_requirement.png) from Pathwright)
 *  No repeating rule
    ```
      display: flex;
      align-items: center;
   ```

2020-05-16 04:17 UTC, rammazzoti2000 commented on assets/styles.css
> +.input-div {
CSS bad practices ([article for support ](https://speckyboy.com/good-bad-css-practices)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/css_bad_practices_requirement.png) from Pathwright)
 *  No repeating rule
    ```
      display: flex;
      align-items: center;
   ```

2020-05-16 04:17 UTC, rammazzoti2000 commented on assets/styles.css
> +footer {
CSS bad practices ([article for support ](https://speckyboy.com/good-bad-css-practices)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/css_bad_practices_requirement.png) from Pathwright)
 *  No repeating rule
    ```
      display: flex;
      justify-content: center;
   ```

2020-05-16 04:17 UTC, rammazzoti2000 commented on assets/styles.css
> +.useful_links ul {
CSS bad practices ([article for support ](https://speckyboy.com/good-bad-css-practices)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/css_bad_practices_requirement.png) from Pathwright)
 *  No repeating rule
    ```
      display: flex;
      justify-content: center;
   ```

2020-05-16 04:17 UTC, rammazzoti2000 requested changes
### :stop_sign: Status: Required Changes

2020-05-18 01:39 UTC, wrakc commented
I fixed the horizontal overflow left according to the suggestion;
I fixed the CSS bad practices according to the inline comments.

2020-05-18 01:41 UTC, wrakc commented
- I fixed the horizontal overflow left according to the suggestion;
- I fixed the CSS bad practices according to the inline comments;
- Fixed some linter errors.

2020-05-18 23:49 UTC, christianotieno approved these changes
# PROJECT APPROVED :champagne:
Excellent job on this project guys. :fireworks:  Keep it up.
##
### The [clone](https://raw.githack.com/wrakc/apple-clone/feature/index.html) shows good understanding and usage of building with backgrounds and gradients. :100:
##
- The cloned page is rendering as it should and meets all the project specifications.
-  The project has a descriptive README.md and is professionally done. Good job with that.
- Pull Request has a meaningful title and a short description.
- CSS is clean. No linter errors at this point and no bad practices used as well.
- The markup as well has no errors nor warnings to show. Good job with that.
- The repo has followed all the guidelines there are to follow (GitHub flow etc.)
**All the required tasks have been fulfilled in this project. I will go ahead and mark this as complete.**
- Congratulations on the splendid job @wrakc! :+1:
- You can now merge to master and I wish you all the very best in your next tasks 🥇
##
Happy coding :smile:
**[Christian Otieno](https://github.com/ChristianOtieno)**
[Twitter](https://twitter.com/iamchrisotieno) [linkedin](https://www.linkedin.com/in/christianotieno/) [GitLab](https://gitlab.com/christianotieno)

2020-05-19 01:48 UTC, merged